image: python:3.9.2

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip
    - venv/

before_script:
  - python -V
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate
  - pip install -r requirements.txt

stages:
  - test
  - build
  - deploy

test:
  stage: test
  script:
    - python setup.py test

build:
  stage: build
  artifacts:
    paths:
      - build
      - dist
  script:
    - pip install --upgrade build
    - python -m build

deploy:
  stage: deploy
  script:
    - pip install --upgrade build twine
    - python -m build
    # Edit the below line
    - TWINE_PASSWORD=${CI_JOB_TOKEN} TWINE_USERNAME=gitlab-ci-token python -m twine upload --repository-url https://gitlab.domain.com/api/v4/projects/${CI_PROJECT_ID}/packages/pypi dist/*
  allow_failure: false
